---
- name: Create application directory
  file:
    path: /home/{{ ansible_user }}/nginx-ffmpeg
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create HTML directory
  file:
    path: /home/{{ ansible_user }}/nginx-ffmpeg/html
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy Nginx configuration file
  template:
    src: default.conf.j2
    dest: /home/{{ ansible_user }}/nginx-ffmpeg/default.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /home/{{ ansible_user }}/nginx-ffmpeg/default.conf:/etc/nginx/conf.d/default.conf
      - /home/{{ ansible_user }}/nginx-ffmpeg/html:/usr/share/nginx/html
