---
- name: Create application directory
  file:
    path: /opt/nginx-ffmpeg
    state: directory

- name: Create HTML directory
  file:
    path: /opt/nginx-ffmpeg/html
    state: directory

- name: Copy Nginx configuration file
  template:
    src: default.conf.j2
    dest: /opt/nginx-ffmpeg/default.conf

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - /opt/nginx-ffmpeg/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/nginx-ffmpeg/html:/usr/share/nginx/html
