- name: Create application directory
  file:
    path: "/home/{{ ansible_user }}/nginx-ffmpeg"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create HTML directory
  file:
    path: "{{ nginx_html_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy Nginx configuration file
  template:
    src: default.conf.j2
    dest: "{{ nginx_config_path }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Run Nginx container
  docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image }}"
    state: started
    restart_policy: always
    ports: "{{ nginx_ports }}"
    volumes:
      - "{{ nginx_config_path }}:/etc/nginx/conf.d/default.conf:ro"
      - "{{ nginx_html_path }}:/usr/share/nginx/html:ro"
    env:
      NGINX_HOST: "localhost"
      NGINX_PORT: "80"
    networks:
      - name: bridge

- name: Ensure Nginx container is running
  docker_container_info:
    name: "{{ nginx_container_name }}"
  register: container_info

- name: Print container status
  debug:
    msg: "Nginx container is {{ container_info.container.State.Status }}"