---
- name: Create application directory
  file:
    path: "{{ nginx_ffmpeg_base_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create HTML directory
  file:
    path: "{{ nginx_ffmpeg_html_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Run FFmpeg container
  docker_container:
    name: "{{ ffmpeg_container_name }}"
    image: "{{ ffmpeg_image }}"
    state: started
    restart_policy: always
    command: "{{ ffmpeg_command }}"
    volumes:
      - "{{ nginx_ffmpeg_html_path }}:/frames"