---
- name: Create application directory
  file:
    path: /home/{{ ansible_user }}/nginx-ffmpeg
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create HTML directory
  file:
    path: /home/{{ ansible_user }}/nginx-ffmpeg/html
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Run FFmpeg container
  docker_container:
    name: ffmpeg
    image: jrottenberg/ffmpeg:latest
    state: started
    restart_policy: always
    command: >
      -i http://webcam.mchcares.com/mjpg/video.mjpg -vf fps=1 /frames/index.jpg -y
    volumes:
      - /home/{{ ansible_user }}/nginx-ffmpeg/html:/frames
